config/routes.rb
Repeatsurvey::Application.routes.draw do

  root :to => "programs#current"

  namespace :admin do
    resources :values do as_routes end
    resources :questions do as_routes end
    resources :respondents do as_routes end
    resources :programs do as_routes end
    resources :rounds do as_routes end
  end

  resources :programs do
    match 'reports/report1' => 'reports#report1', as: :reports
    resources :rounds  do
      member do
        get 'report'
      end
    end
    resources :respondents
    resources :questions
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :text, :order
  belongs_to :program
  has_many :respondents, through: :values
  has_many :values

  validates_presence_of :text, :order

  def average round
      Value.where("round_id = ? AND question_id = ?", round.id, id).average("value")
  end

  def n_respondents round
      Value.where("round_id = ? AND question_id = ?", round.id, id).count("value")
   end

   def short_name
    "Question #{order}"
  end
end

app/controllers/admin/questions_controller.rb
module Admin
	class QuestionsController < ApplicationController
		active_scaffold :question do |config|
		end
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @questions_list = questions_list.new(params[:program_report])
    @ql_assets = @questions_list.assets.paginate(page: params[:page].merge(order: {tab: "questions"}))
  end

  def new
    @program = Program.find(params[:program_id])
    @question = @program.questions.build
    respond_with(@question)
  end

  def create  
    @program = Program.find(params[:program_id])
    @question = @program.questions.new(params[:question])  
    if @question.save  
      redirect_to program_path(@program,  tab: 'questions'), 
                  notice: "Successfully created question."
    else  
      render :action => 'new'  
    end  
  end  

  def show
    @program = Program.find(params[:program_id])
    @question = Question.find(params[:id])
    respond_with(@program, @question)
  end

  def edit
    @question = Question.find(params[:id])
    @program = Program.find(params[:program_id])
  end

  def update
    @program = Program.find(params[:program_id])
    @question = @program.questions.find(params[:id])  
    if @question.update_attributes(params[:question])  
      flash[:notice] = "Successfully updated question."  
    end  
    respond_with(:program, @question)  
  end  

  def destroy
    puts params
    @question = Question.find(params[:id])  
    @question.destroy  
    flash[:notice] = "Question deleted."  
    respond_with(:program, @question)  
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= simple_form_for [@program, @question], 
    url: program_questions_path(@program, tab: 'questions'), 
    method: :post,
    html: {  class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>
      <%= controller.action_name.capitalize %> Question
    </legend>

    <%= f.input :text %>
    <%= f.input :order %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', program_path(@program, tab: "questions"), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/questions/_question.html.erb
<tr>
   <td><%= question.order %></td>
   <td><%= question.text %></td>
   <td><%= question.active %></td>
   <td><%= question.respondents.select(:name).uniq.length %></td>
   <td><%= question.data_type%></td>
   <td>
      <%= link_to t('.show'), program_question_path(@program, question), 
          :class => 'btn btn-mini' %> | 
      <%= link_to t('.edit'), edit_program_question_path(@program, question), 
          :class => 'btn btn-mini' %> |
      <%= link_to t('delete'), program_question_path(@program, question), 
          :method => :delete, 
          :confirm => "are you sure?",
          :class => 'btn btn-mini btn-danger' %>
    </td>
</tr>

app/views/questions/_question_for_round.html.erb
<tr>
   <td><%= question.text %></td>
   <td><%= f2s(question.average(@round)) %></td>
   <td><%= question.n_respondents @round %></td>
</tr>

app/views/questions/delete.html.erb
<h1>Questions#delete</h1>
<p>Find me in app/views/questions/delete.html.erb</p>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Back', program_questions_path(@program) %>
<%= link_to 'Show', [@program, @question] %> |

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>
<%= link_to 'Back', program_path(@program, tab:"questions") %>

app/views/questions/show.html.erb
<div class="page-header">
   <h1>Program '<%= @question.text %>'</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Question text</strong></dt>
  <dd><%= @question.text %></dd>
  <dt><strong>Order:</strong></dt>
  <dd><%= @question.order %></dd>
</dl>

<div class="form-actions">
  <%= link_to "Back", programs_path(@program, tag: "questions"), class: "btn" %>
  <%= link_to "Edit", edit_program_question_path(@program, @question), class: "btn" %>
  <%= link_to "Delete", program_question_path(@program, @question), 
              method: 'delete',
              confirm: 'Are you sure?',
              class: 'btn btn-danger' %>
</div>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>