config/routes.rb
Repeatsurvey::Application.routes.draw do

  root :to => "programs#current"

  namespace :admin do
    resources :values do as_routes end
    resources :questions do as_routes end
    resources :respondents do as_routes end
    resources :programs do as_routes end
    resources :rounds do as_routes end
  end

  resources :programs do
    match 'reports/report1' => 'reports#report1', as: :reports
    resources :rounds  do
      member do
        get 'report'
      end
    end
    resources :respondents
    resources :questions
  end

end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :name
  has_many :rounds
  has_many :questions
  has_many :respondents
end

app/controllers/admin/programs_controller.rb
module Admin
	class ProgramsController < ApplicationController
		active_scaffold :program do |config|
		end
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  respond_to :html, :xml, :json, :js
  def show
    @program = Program.find(params[:id])
    show_program
  end

  def current
    @program = Program.first
    show_program
  end

  def new
    @program = Program.new
    respond_with(@program)
  end

  def show_program
    @respondents = @program.respondents
    @questions = @program.questions
    @rounds = @program.rounds
    @questions_grid = QuestionsGrid.new(params[:questions_grid])
    @qg_assets = @questions_grid.assets.paginate(page: params[:page])

    respond_with([:program => @program, :respondents => @respondents, 
                 :question => @questions, :rounds => @rounds], 
                 :template => 'programs/show')
  end

  def index
    @programs_grid = ProgramsGrid.new(params[:programs_grid])
    @assets = @programs_grid.assets.page(params[:page])
  end

end

app/helpers/programs_helper.rb
module ProgramsHelper
  def reports_list( options = {}, &proc)
    reports_list = ReportsListRenderer.new(self)
    @content = capture(reports_list, &proc)
    content_tag(:div, @content, class: 'container')
  end
end

app/views/programs/_form.html.erb
<%= simple_form_for @program, :html => { :class => 'form-horizontal'} do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Program</legend>

    <%= f.input :name %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', program_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/programs/_program_tab_headers.html.erb
<ul class="nav nav-tabs">
   <li class="<%= 'active' if (params[:tab] == 'reports'  || !params[:tab]) %>">
      <a href="#report-pane" data-toggle="tab">Reports</a>
   </li>
   <li class="<%= 'active' if params[:tab] == 'summary' %>">
      <a href="#summary-pane" data-toggle="tab">Summary Stats</a>
   </li>
   <li class="<%= 'active' if params[:tab] == 'rounds' %>">
      <a href="#round-pane" data-toggle="tab">Rounds</a>
   </li>
   <li class="<%= 'active' if params[:tab] == 'settings' %>">
      <a href="#setting-pane" data-toggle="tab">Settings</a>
   </li>
   <li class="<%= 'active' if params[:tab] == 'questions' %>">
      <a href="#question-pane" data-toggle="tab">Questions</a>
   </li>
   <li class="<%= 'active' if params[:tab] == 'participants' %>">
      <a href="#participant-pane" data-toggle="tab">Partipants</a>
   </li>
</ul>

app/views/programs/_questions_pane.html.erb
<h2> Question </h2>
<p>Each survey has a series of questions. Generally they are quantitative, for example for a rating or an amount. This is in the nature of this product, which is to analyze a recurrent survey over a series of rounds and to produce longitudinal statistics.</p>
<p>Best practice is not to change the set of questions once the survey is underway. However you often find that you decide on new questions you want to ask as the study proceeds.</p>
<p>From this screen you may add new questions, and also activate and deactivate questions during the study. However note well that the statistics are a little more difficult to interpret when questions appear and dissappear during the surveys lifetime.</p>
<table class="table table-condensed table-bordered">
   <thead>
      <tr>
         <th>Number</th>
         <th>Text</th>
         <th>Active</th>
         <th>Responses so far</th>
         <th>Data Type</th>
         <th><%=t('.actions') %></th>
      </tr>
   </thead>
   <tbody>
      <%= render @questions || "There are no rounds yet" %>
   </tbody>
</table>
<%= link_to t('.new'), new_program_question_path(@program),
:class => 'btn btn-primary' %>

app/views/programs/_reports_pane.html.erb
<script>
  $(function() {
    $('#reports').bind('show', function(e) {
      if ($(e.target).attr('id') == 'reports-navlist')
        $.ajax({
          url: '<%= program_reports_path(@program) -%>',
          data: { toggle: "tab" }, 
          success: function(html){
            $("div#report-html-content").html(html);
          }
        })
    });
  });
</script>

<div class="container">
  <div class="row">
    <div class="span2">
      <ul class="nav nav-pills nav-stacked" id="reports">
        <li>
          <a href="#" data-toggle="pill">Trend lines for all questions</a>
        </li>
        <li>
          <a href="#" data-toggle="pill" id="reports-navlist">Summart of all queries</a>
        </li> 
        <li class="active">
          <a href="#" data-toggle="pill">Trend lines for all questions</a>
        </li>
        <li>
          <a href="#" data-toggle="pill">Details on all questions</a>
        </li>
      </ul>
    </div>
    <div class="span10" id="report-html-content">
    </div>
  </div>
</div>

app/views/programs/_rounds_pane.html.erb
<h2> Rounds </h2>
<p>Each round corresponds to one round of responses to the survey from all participants. Rounds occur on a periodic basis, say once a week.</p>
<table class="table table-condensed table-bordered">
   <thead>
      <tr>
         <th>Round number</th>
         <th>Status</th>
         <th>Responses so far</th>
         <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
   </thead>
   <tbody>
      <%= render @rounds || "There are no rounds yet" %>
   </tbody>
</table>
<%= link_to t('.new', :default => t("helpers.links.new")),
new_program_round_path(@program),
:class => 'btn btn-primary' %>

app/views/programs/index.html.erb
<div class="page-header">
  <h1>Welcome to SurveyLogic</h1>
</div>
<h3>Programs</h3>
<div>
  <%= datagrid_table(@programs_grid, @pg_assets, 
      {html: 
        {class: "table table-bordered table-compressed"}})
  %>

  <%= link_to new_program_path, class: "btn btn-small" do %>
    <%= content_tag(:i, "", class: "icon-info-sign") %>
    New Program
  <% end %>



</div>

app/views/programs/new.html.erb
<%= render :partial => 'form' %>

app/views/programs/save_reports_pane.html.erb
<div class="container">
  <div class="row">
    <div class="span2">
      <ul class="nav nav-tabs nav-stacked" id="reports-navlist">
        <li class="active" id="rep-all-q">
          <%= link_to "Summary of all questions", program_reports_path(@program), 
                    :remote => true, id: "reports-navlist", data: {toggle: "tab"} %>
        </li>
        <li id="rep-trend-q">
          <a href="#" data-toggle="tab">Trend lines for all questions</a>
        </li>
        <li id="rep-det-all-q">
          <a href="#" data-toggle="tab">Details on all questions</a>
        </li>
      </ul>
    </div>
    <div class="span10" id="report-html-content">
    </div>
  </div>
</div>

app/views/programs/show.html.erb
<div class="page-header">
   <h1>Program '<%= @program.name %>'</h1>
</div>

<div class="tabbable">
   <%= render "program_tab_headers" %>

   <div class="tab-content">
      <div class="<%= if (params[:tab] == 'tab1' || !params[:tab]) then 'tab-pane active'  else 'tab-pane' end%>" id="report-pane">
         <%= render 'reports_pane' %>
      </div>
      <div class="<%= if params[:tab] == 'summary' then 'tab-pane active'  else 'tab-pane' end%>" id="summary-pane">
         <h3>Summary Statistics</h3>
      </div>
      <div class="<%= if (params[:tab] == 'settings') then 'tab-pane active'  else 'tab-pane' end%>" id="setting-pane">
         <h3>Project Settings</h3>
      </div>
      <div class="<%= if (params[:tab] == 'participants')then 'tab-pane active'  else 'tab-pane' end%>" id="participant-pane">
         <h3>Participants</h3>
         <table class="table table-condensed table-bordered">
            <thead>
               <tr>
                  <th>Participant Name</th>
               </tr>
            </thead>
            <tbody>
               <%= render @respondents || "There are no Participant yet" %>
            </tbody>
         </table>
      </div>
      <div class="<%= if (params[:tab] == 'questions') then 'tab-pane active'  else 'tab-pane' end%>" id="question-pane">
         <%= render 'questions_pane' %>
      </div>
      <div class="<%= if (params[:tab] == 'rounds' )then 'tab-pane active'  else 'tab-pane' end%>" id="round-pane">
         <%= render 'rounds_pane' %>
      </div>
   </div>
</div>
<%= debug_enable false, @program, @respondents, @questions %>