config/routes.rb
Repeatsurvey::Application.routes.draw do

  root :to => "programs#current"

  namespace :admin do
    resources :values do as_routes end
    resources :questions do as_routes end
    resources :respondents do as_routes end
    resources :programs do as_routes end
    resources :rounds do as_routes end
  end

  resources :programs do
    match 'reports/report1' => 'reports#report1', as: :reports
    resources :rounds  do
      member do
        get 'report'
      end
    end
    resources :respondents
    resources :questions
  end

end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :number, :program_id, :start, :fin
  belongs_to :program
  has_many :respondents, through: :values
  has_many :values

  def short_name
    "round #{number}"
  end
end

app/controllers/admin/rounds_controller.rb
module Admin
	class RoundsController < ApplicationController
		active_scaffold :round do |config|
		end
	end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
	respond_to :html, :xml

	def report
     	@program = Program.find_by_id(params[:program_id])
     	@round = Round.find_by_id(params[:id])
      @questions = @program.questions.paginate(:page => params[:quest_page])
#      @questions = @program.questions
      respond_with(@round, @program, @questions)
  end

  def show
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_round.html.erb
<tr>
   <td><%= round.number %></td>
   <td><%= round.status %></td>
   <td><%= round.respondents.select(:name).uniq.length %></td>
   <td>
      <%= link_to t('.show'), program_round_path(round, @program), 
          :class => 'btn btn-mini' %> | 
      <%= link_to t('.edit'), edit_program_round_path(@program, round), 
          :class => 'btn btn-mini' %> |
      <%= link_to t('.delete'), program_round_path(round, @program), 
          :method => :delete, 
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
          :class => 'btn btn-mini btn-danger' %>
    </td>
</tr>

app/views/rounds/report.html.erb
<h1>Round <%= @round.number %> for <%= link_to(("Program '" + @program.name + "'"), program_path(@program)) %></h1>

<table class="table table-bordered table-condensed display">
   <thead>
      <tr>
         <th>Question</th>
         <th>Average</th>
         <th>Count</th>
      </tr>
   </thead>
   <tbody>
      <%= render(partial: "questions/question_for_round", 
                 collection: @questions, as: :question) %>
   </tbody>
</table>
   
<%= will_paginate (@questions) %>