config/routes.rb
Repeatsurvey::Application.routes.draw do

  root :to => "programs#current"

  namespace :admin do
    resources :values do as_routes end
    resources :questions do as_routes end
    resources :respondents do as_routes end
    resources :programs do as_routes end
    resources :rounds do as_routes end
  end

  resources :programs do
    match 'reports/report1' => 'reports#report1', as: :reports
    resources :rounds  do
      member do
        get 'report'
      end
    end
    resources :respondents
    resources :questions
  end

end

app/models/respondent.rb
class Respondent < ActiveRecord::Base
  attr_accessible :name
  belongs_to :program
end

app/controllers/admin/respondents_controller.rb
module Admin
	class RespondentsController < ApplicationController
		active_scaffold :respondent do |config|
		end
	end
end

app/controllers/respondents_controller.rb
class RespondentsController < ApplicationController
  respond_to :html, :xml, :json

  def show
    @respondent = Respondent.find(params[:id])
    @program = @respondent.program
    @questions = @program.questions
    respond_with(:respondents => @respondents)
  end

  def index
  end
end

app/helpers/respondents_helper.rb
module RespondentsHelper
  def line_sparkline_markup(title, data)
    content_tag(:span, data.join(","),:class => "inlinesparkline") + 
    content_tag(:br) + 
    content_tag(:span, title)
  end
end

app/views/respondents/_respondent.html.erb
<tr>
   <td><%= link_to(respondent.name, program_respondent_path(@program, respondent)) %></td>
</tr>

app/views/respondents/show.html.erb
<h2>Respondent: <%= @respondent.name %></h2>
  <p>This respondent has answered at least some of the questions asked as part of this program: <%= @program.name %>. 
  </p>
  <p>There were <%= @questions.length %> questions total, although notice that in each round not all questions are always asked. 
  </p>
  <p>Note that the organizer might add or disable questions for one round or another, although that would be unusual. </p>

    <h3>Summary of responses across all rounds for <%= @respondent.name %></h4>

    <table class="table table-condensed table-bordered">
      <caption>Trend line of response for each question.</caption>
      <thead></thead>
      <tbody>
        <% @questions.in_groups_of(5) do |group| %>
          <tr>
            <% group.each do |item| %>
              <td>
                <% if !item.nil? %>
                  <% data = DatabaseDataCache.get(question: item.id,   respondent: @respondent.id, round: :all) %>
                  <%= line_sparkline_markup(item.text, data) %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>